apiVersion: v1
kind: Namespace
metadata:
  name: stage
  labels:
    namespace: stage
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: fb
  name: fb
  namespace: stage
spec:
  selector:
    matchLabels:
      app: fb
  replicas: 1
  template:
    metadata:
      labels:
        app: fb
    spec:
      initContainers:
      - name: wait-for-db
        image: postgres:13-alpine
        command: [ "sh", "-c", "until pg_isready -h db -p 5432 -U postgres:postgres; do echo 'not yet'; sleep 2; done" ]
      containers:
      - image: kostidan/backend:stage
        imagePullPolicy: IfNotPresent
        name: backend
      - image: kostidan/frontend:stage
        imagePullPolicy: IfNotPresent
        name: frontend