apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: backend-app
  name: backend-app
  namespace: prod
spec:
  selector:
    matchLabels:
      app: backend-app
  replicas: 1
  template:
    metadata:
      labels:
        app: backend-app
    spec:
      initContainers:
      - name: wait-for-db
        image: postgres:13-alpine
        command: [ "sh", "-c", "until pg_isready -h db -p 5432 -U postgres:postgres; do echo 'not yet'; sleep 2; done" ]
      containers:
      - image: kostidan/backend:stage
        imagePullPolicy: IfNotPresent
        name: backend
        env:
          - name: DATABASE_URL
            value: postgres://postgres:postgres@db:5432/news
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: backend-app
  name: backend-app
  namespace: prod
spec:
  type: ClusterIP
  ports:
  - name: backend-app
    port: 9000
    protocol: TCP
    targetPort: 9000
  selector:
    app: backend-app