apiVersion: v1
kind: Namespace
metadata:
  name: prod
  labels:
    namespace: prod
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: frontend-app
  name: frontend-app
  namespace: prod
spec:
  selector:
    matchLabels:
      app: frontend-app
  replicas: 1
  template:
    metadata:
      labels:
        app: frontend-app
    spec:
      containers:
      - image: kostidan/frontend:stage
        imagePullPolicy: IfNotPresent
        name: frontend
        env:
          - name: BASE_URL
            value: http://backend-app:9000
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: frontend-app
  name: frontend-app
  namespace: prod
spec:
  type: ClusterIP
  ports:
  - name: frontend-app
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: frontend-app