all:
  hosts:
    cp1:
      ansible_host: 51.250.10.214
      ansible_user: yc-user
    node1:
      ansible_host: 51.250.5.116
      ansible_user: yc-user
    node2:
      ansible_host: 51.250.91.168
      ansible_user: yc-user
    node3:
      ansible_host: 51.250.1.1
      ansible_user: yc-user
    node4:
      ansible_host: 51.250.14.22
      ansible_user: yc-user
  children:
    kube_control_plane:
      hosts:
        cp1:
    kube_node:
      hosts:
        node1:
        node2:
        node3:
        node4:
    etcd:
      hosts:
        cp1:
    k8s_cluster:
      children:
        kube_control_plane:
        kube_node:
    calico_rr:
      hosts: {}
